spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/highlights
    driverClassName: org.postgresql.Driver
    username: highlights
    password: highlights
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  servlet:
    context-path: /highlights
